version: "3.8"

services:
  laravel-backend:
    image: sielea1/cco-laravel-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - .env:/var/www/.env
    networks:
      - laravel_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  worker:
    image: sielea1/cco-worker:latest
    volumes:
      - .:/var/www
      - .env:/var/www/.env
    command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=90"]
    networks:
      - laravel_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    networks:
      - laravel_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  laravel_network:
    driver: overlay

volumes:
  db-data:
